version: '2'
services:
    etat_civil-app:
        image: etat_civil
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://etat_civil-mysql:3306/etat_civil?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=etat_civil-elasticsearch:9300
        ports:
            - 8080:8080
    etat_civil-mysql:
        extends:
            file: mysql.yml
            service: etat_civil-mysql
    etat_civil-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: etat_civil-elasticsearch
